/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 50622
 Source Host           : localhost:3306
 Source Schema         : une

 Target Server Type    : MySQL
 Target Server Version : 50622
 File Encoding         : 65001

 Date: 09/02/2021 18:28:35
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for book
-- ----------------------------
DROP TABLE IF EXISTS `book`;
CREATE TABLE `book`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `author` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `summary` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `image` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `delete_time` datetime(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for lin_file
-- ----------------------------
DROP TABLE IF EXISTS `lin_file`;
CREATE TABLE `lin_file`  (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'LOCAL' COMMENT 'LOCAL 本地，REMOTE 远程',
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `extension` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `size` int(11) NULL DEFAULT NULL,
  `md5` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'md5值，防止上传重复文件',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `delete_time` datetime(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `md5_del`(`md5`, `delete_time`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for lin_group
-- ----------------------------
DROP TABLE IF EXISTS `lin_group`;
CREATE TABLE `lin_group`  (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '分组名称，例如：搬砖者',
  `info` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '分组信息：例如：搬砖的人',
  `level` tinyint(2) NOT NULL DEFAULT 3 COMMENT '分组级别 1：root 2：guest 3：user（root、guest分组只能存在一个)',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `delete_time` datetime(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `name_del`(`name`, `delete_time`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of lin_group
-- ----------------------------
INSERT INTO `lin_group` VALUES (1, 'root', '超级用户组', 1, '2021-01-26 23:20:39.560', '2021-01-26 23:20:39.560', NULL);
INSERT INTO `lin_group` VALUES (2, 'guest', '游客组', 2, '2021-01-26 23:20:39.560', '2021-01-26 23:20:39.560', NULL);

-- ----------------------------
-- Table structure for lin_group_permission
-- ----------------------------
DROP TABLE IF EXISTS `lin_group_permission`;
CREATE TABLE `lin_group_permission`  (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_id` int(10) UNSIGNED NOT NULL COMMENT '分组id',
  `permission_id` int(10) UNSIGNED NOT NULL COMMENT '权限id',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `group_id_permission_id`(`group_id`, `permission_id`) USING BTREE COMMENT '联合索引'
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for lin_log
-- ----------------------------
DROP TABLE IF EXISTS `lin_log`;
CREATE TABLE `lin_log`  (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `message` varchar(450) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `user_id` int(10) UNSIGNED NOT NULL,
  `username` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `status_code` int(11) NULL DEFAULT NULL,
  `method` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `path` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `permission` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `delete_time` datetime(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for lin_permission
-- ----------------------------
DROP TABLE IF EXISTS `lin_permission`;
CREATE TABLE `lin_permission`  (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '权限名称，例如：访问首页',
  `module` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '权限所属模块，例如：人员管理',
  `mount` tinyint(1) NOT NULL DEFAULT 1 COMMENT '0：关闭 1：开启',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `delete_time` datetime(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 12 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of lin_permission
-- ----------------------------
INSERT INTO `lin_permission` VALUES (1, '查询所有日志', '日志', 1, '2021-01-26 23:23:34.000', '2021-01-26 23:23:34.000', NULL);
INSERT INTO `lin_permission` VALUES (2, '搜索日志', '日志', 1, '2021-01-26 23:23:34.000', '2021-01-26 23:23:34.000', NULL);
INSERT INTO `lin_permission` VALUES (3, '查询日志记录的用户', '日志', 1, '2021-01-26 23:23:34.000', '2021-01-26 23:23:34.000', NULL);
INSERT INTO `lin_permission` VALUES (4, '测试日志记录', '信息', 1, '2021-01-26 23:23:34.000', '2021-01-26 23:23:34.000', NULL);
INSERT INTO `lin_permission` VALUES (5, '查看lin的信息', '信息', 1, '2021-01-26 23:23:34.000', '2021-01-26 23:23:34.000', NULL);
INSERT INTO `lin_permission` VALUES (6, '删除图书', '图书', 1, '2021-01-26 23:23:34.000', '2021-01-26 23:23:34.000', NULL);
INSERT INTO `lin_permission` VALUES (7, '删除视频分类', '视频分类', 1, '2021-01-26 23:23:34.000', '2021-01-26 23:23:34.000', NULL);
INSERT INTO `lin_permission` VALUES (8, '删除视频', '视频', 1, '2021-01-26 23:23:34.000', '2021-01-26 23:23:34.000', NULL);
INSERT INTO `lin_permission` VALUES (9, '删除图书', '广告', 0, '2021-02-05 00:46:38.000', '2021-02-05 00:49:21.000', NULL);
INSERT INTO `lin_permission` VALUES (10, '删除广告', '广告', 1, '2021-02-05 00:49:21.000', '2021-02-05 00:49:21.000', NULL);
INSERT INTO `lin_permission` VALUES (11, '删除资料', '资料', 1, '2021-02-09 00:02:41.000', '2021-02-09 00:02:41.000', NULL);

-- ----------------------------
-- Table structure for lin_user
-- ----------------------------
DROP TABLE IF EXISTS `lin_user`;
CREATE TABLE `lin_user`  (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '用户名，唯一',
  `nickname` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户昵称',
  `avatar` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '头像url',
  `email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '邮箱',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `delete_time` datetime(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `username_del`(`username`, `delete_time`) USING BTREE,
  UNIQUE INDEX `email_del`(`email`, `delete_time`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of lin_user
-- ----------------------------
INSERT INTO `lin_user` VALUES (1, 'root', 'root', NULL, NULL, '2021-01-26 23:20:39.558', '2021-01-26 23:20:39.558', NULL);

-- ----------------------------
-- Table structure for lin_user_group
-- ----------------------------
DROP TABLE IF EXISTS `lin_user_group`;
CREATE TABLE `lin_user_group`  (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int(10) UNSIGNED NOT NULL COMMENT '用户id',
  `group_id` int(10) UNSIGNED NOT NULL COMMENT '分组id',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `user_id_group_id`(`user_id`, `group_id`) USING BTREE COMMENT '联合索引'
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of lin_user_group
-- ----------------------------
INSERT INTO `lin_user_group` VALUES (1, 1, 1);

-- ----------------------------
-- Table structure for lin_user_identity
-- ----------------------------
DROP TABLE IF EXISTS `lin_user_identity`;
CREATE TABLE `lin_user_identity`  (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int(10) UNSIGNED NOT NULL COMMENT '用户id',
  `identity_type` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `identifier` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `credential` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `delete_time` datetime(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of lin_user_identity
-- ----------------------------
INSERT INTO `lin_user_identity` VALUES (1, 1, 'USERNAME_PASSWORD', 'root', 'sha1$c419e500$1$84869e5560ebf3de26b6690386484929456d6c07', '2021-01-26 23:20:39.559', '2021-01-26 23:20:39.559', NULL);

-- ----------------------------
-- Table structure for une-read
-- ----------------------------
DROP TABLE IF EXISTS `une-read`;
CREATE TABLE `une-read`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `url` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `create_time` datetime(0) NOT NULL,
  `update_time` datetime(0) NOT NULL,
  `delete_time` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of une-read
-- ----------------------------
INSERT INTO `une-read` VALUES (1, '142141242141', 'http://une.sven-it.com/pdf/SpringBoot%E5%90%AF%E5%8A%A8%E6%B5%81%E7%A8%8B%E8%A7%A3%E6%9E%90.pdf', '2021-02-09 00:08:14', '2021-02-09 00:08:14', NULL);
INSERT INTO `une-read` VALUES (2, '大萨达大多', 'http://une.sven-it.com/pdf/SpringBoot%E5%90%AF%E5%8A%A8%E6%B5%81%E7%A8%8B%E8%A7%A3%E6%9E%90.pdf', '2021-02-09 00:13:06', '2021-02-09 00:13:06', NULL);

-- ----------------------------
-- Table structure for une-swipe
-- ----------------------------
DROP TABLE IF EXISTS `une-swipe`;
CREATE TABLE `une-swipe`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `image` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `url` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `order` int(11) NULL DEFAULT NULL,
  `create_time` datetime(0) NOT NULL,
  `update_time` datetime(0) NOT NULL,
  `delete_time` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of une-swipe
-- ----------------------------
INSERT INTO `une-swipe` VALUES (1, 'http://une.sven-it.com/FszZwHlBGTWtMGOXiRTrXggzr-7T', 'https://youzan.github.io/vant/#/zh-CN/notify', NULL, '2021-02-05 01:19:04', '2021-02-05 01:19:04', NULL);
INSERT INTO `une-swipe` VALUES (2, 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'https://youzan.github.io/vant/#/zh-CN/notify', NULL, '2021-02-05 01:19:11', '2021-02-05 01:19:11', NULL);

-- ----------------------------
-- Table structure for une_order
-- ----------------------------
DROP TABLE IF EXISTS `une_order`;
CREATE TABLE `une_order`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `vedio_id` int(11) NOT NULL,
  `out_trade_no` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `time_expire` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `total` int(11) NULL DEFAULT NULL,
  `currency` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `openid` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `payer_client_ip` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `status` int(11) NOT NULL DEFAULT 0,
  `create_time` datetime(0) NOT NULL,
  `update_time` datetime(0) NOT NULL,
  `delete_time` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for une_order_type
-- ----------------------------
DROP TABLE IF EXISTS `une_order_type`;
CREATE TABLE `une_order_type`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `order` int(11) NULL DEFAULT NULL,
  `create_time` datetime(0) NOT NULL,
  `update_time` datetime(0) NOT NULL,
  `delete_time` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 11 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of une_order_type
-- ----------------------------
INSERT INTO `une_order_type` VALUES (1, '分类1', 1, '2021-01-26 23:30:05', '2021-01-26 23:30:05', NULL);
INSERT INTO `une_order_type` VALUES (2, '分类2', 2, '2021-01-26 23:30:10', '2021-01-26 23:30:10', NULL);
INSERT INTO `une_order_type` VALUES (3, '分类3', 3, '2021-01-26 23:30:16', '2021-01-26 23:30:16', NULL);
INSERT INTO `une_order_type` VALUES (4, '分类4', 4, '2021-01-26 23:30:30', '2021-01-26 23:30:30', NULL);
INSERT INTO `une_order_type` VALUES (5, '分类5', 5, '2021-01-26 23:30:33', '2021-01-26 23:30:33', NULL);
INSERT INTO `une_order_type` VALUES (6, '分类6', 6, '2021-01-26 23:30:37', '2021-01-26 23:30:37', NULL);
INSERT INTO `une_order_type` VALUES (7, '分类7', 7, '2021-01-26 23:30:40', '2021-01-26 23:30:40', NULL);
INSERT INTO `une_order_type` VALUES (8, '分类8', 8, '2021-01-26 23:30:46', '2021-01-26 23:30:46', NULL);
INSERT INTO `une_order_type` VALUES (9, '分类9', 9, '2021-01-26 23:30:49', '2021-01-26 23:30:49', NULL);
INSERT INTO `une_order_type` VALUES (10, '分类10', 10, '2021-01-26 23:30:55', '2021-01-26 23:30:55', NULL);

-- ----------------------------
-- Table structure for une_vedio
-- ----------------------------
DROP TABLE IF EXISTS `une_vedio`;
CREATE TABLE `une_vedio`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `typeId` int(11) NOT NULL,
  `title` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `author` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '未名',
  `summary` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `image` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `url` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `price` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `create_time` datetime(0) NOT NULL,
  `update_time` datetime(0) NOT NULL,
  `delete_time` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `typeId`(`typeId`) USING BTREE,
  CONSTRAINT `une_vedio_ibfk_1` FOREIGN KEY (`typeId`) REFERENCES `une_order_type` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE = InnoDB AUTO_INCREMENT = 76 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of une_vedio
-- ----------------------------
INSERT INTO `une_vedio` VALUES (1, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (2, 1, '分类2-test1', '分类2-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类2-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '2', '2021-01-26 23:52:05', '2021-01-26 23:52:05', NULL);
INSERT INTO `une_vedio` VALUES (3, 1, '分类3-test1', '分类3-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '3', '2021-01-26 23:58:29', '2021-01-26 23:58:29', NULL);
INSERT INTO `une_vedio` VALUES (4, 1, '分类4-test1', '分类4-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>http://une.sven-it.com/vedio/video1.mp4</p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '22', '2021-01-27 00:00:22', '2021-01-27 00:00:22', NULL);
INSERT INTO `une_vedio` VALUES (6, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (7, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (8, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (9, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (10, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (11, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (12, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (13, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (14, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (15, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (16, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (17, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (18, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (19, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (20, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (21, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (22, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (23, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (24, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (25, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (26, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (27, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (28, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (29, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (30, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (31, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (32, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (33, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (34, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (35, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (36, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (37, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (38, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (39, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (40, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (41, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (42, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (43, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (44, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (45, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (46, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (47, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (48, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (49, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (50, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (51, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (52, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (53, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (54, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (55, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (56, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (57, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (58, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (59, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (60, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (61, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (62, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (63, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (64, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (65, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (66, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (67, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (68, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (69, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (70, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (71, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (72, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (73, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (74, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);
INSERT INTO `une_vedio` VALUES (75, 1, '分类1-test1', '分类1-test1', '<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n<p>分类1-test1</p>\n<p>图1</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图2</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图3</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图4</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n<p>图5</p>\n<p><img src=\"http://une.sven-it.com/image/vedio-cover.jpeg\" alt=\"\" width=\"308\" height=\"205\" /></p>\n</body>\n</html>', 'http://une.sven-it.com/Fo0zRMjNR2-345EGOZn6059qvx9l', 'http://une.sven-it.com/vedio/video1.mp4', '0', '2021-01-26 23:50:46', '2021-01-26 23:50:46', NULL);

-- ----------------------------
-- Table structure for wx_token
-- ----------------------------
DROP TABLE IF EXISTS `wx_token`;
CREATE TABLE `wx_token`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `openid` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `access_token` varchar(300) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `refresh_token` varchar(300) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `expires_in` int(11) NOT NULL,
  `create_time` datetime(0) NOT NULL,
  `update_time` datetime(0) NOT NULL,
  `delete_time` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for wx_user
-- ----------------------------
DROP TABLE IF EXISTS `wx_user`;
CREATE TABLE `wx_user`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `openid` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `nickname` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `sex` varchar(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `province` varchar(300) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `city` varchar(300) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `country` varchar(300) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `headimgurl` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `create_time` datetime(0) NOT NULL,
  `update_time` datetime(0) NOT NULL,
  `delete_time` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

SET FOREIGN_KEY_CHECKS = 1;
